### ISSUE TITLE
Date conversions from strings in US format fail when default culture is  en-gb

### ISSUE THREAD

**Issue by frodofrod** [PaulDSheriff/VSToolbox#1]
The string constants used to initialise date fields cause exceptions if the default culture on the local PC is not en-us. Need to include the culture explicitly in the conversions to work  correctly
eg
BirthDate = Convert.ToDateTime("8/2/1978 12:00:00 AM", new CultureInfo("en-us")),

**Comment by PaulDSheriff** [comment]
Good catch. Thanks!
